/* 
Procedure utilizada para o fechamento de processos dos usuários de acordo com o banco de dados
declarado na variavel @NAMEBASE 
*/
CREATE PROCEDURE SP_KILL_GERAL 
@NAMEBASE VARCHAR(50)
AS

DECLARE @SQL VARCHAR(50) 
DECLARE @MIN INT
DECLARE @MAX INT
DECLARE @PROCESSOKILL SMALLINT 

CREATE TABLE #TEMP 
(
CONTADOR INT IDENTITY NOT NULL,
NAMEBASE VARCHAR(50)  NOT NULL, 
PROCESSO int NOT NULL

PRIMARY KEY(CONTADOR)

)


INSERT INTO #TEMP 
SELECT 
	D.NAME AS NAMEBASE, 
	P.SPID AS PROCESSO FROM SYSDATABASES D INNER JOIN SYSPROCESSES P ON D.DBID = P.DBID 
WHERE D.NAME = @NAMEBASE


SELECT 
	@MIN = MIN(CONTADOR),
	@MAX = MAX(CONTADOR)
FROM 
	#TEMP

WHILE (@MIN <= @MAX)
BEGIN 

SELECT 
	@PROCESSOKILL = PROCESSO FROM 
	#TEMP 
WHERE CONTADOR = @MIN


SET @SQL = 'KILL ' + CAST(@PROCESSOKILL AS VARCHAR)
EXEC (@SQL)

SET @MIN = @MIN + 1
END  


